project:
  type: website

website:
  title: "notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/abittechnical/notes
      - icon: twitter
        href: https://twitter.com/bitwhys
format:
  html:
    theme: litera
    css: styles.css
highlight-style: dracula
execute:
  freeze: auto